2024-12-11 22:04:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-12 03:16:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-12-12 03:22:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-12 03:40:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-13 00:57:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-13 21:51:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-14 03:39:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-16 03:44:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-16 19:26:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-16 19:34:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-16 19:38:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-16 19:43:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-16 19:45:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-16 21:07:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-17 00:30:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-17 01:45:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-17 19:11:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-17 23:33:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-18 02:41:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-18 17:00:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-18 17:04:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-18 17:06:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-18 20:35:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-18 20:39:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.4.0.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.4.0.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.4.0.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:109)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:104)
	at AxInventoryRestore-3.4.0.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
